apiVersion: v1
kind: Service
metadata:
  name: dolphinscheduler-api
  namespace: lakehouse
  labels:
    app: dolphinscheduler-api
spec:
  type: NodePort
  ports:
    - port: 12345
      targetPort: 12345
      name: api
      nodePort: 30125
  selector:
    app: dolphinscheduler-api
