apiVersion: v1
kind: Secret
metadata:
  name: dolphinscheduler-secret
  namespace: lakehouse
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "dolphinscheduler"
  SPRING_DATASOURCE_PASSWORD: "ds123"
