apiVersion: v1
kind: Secret
metadata:
  name: minio-configuration
  namespace: lakehouse
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER=minioadmin
    export MINIO_ROOT_PASSWORD=minioadmin
    export MINIO_BROWSER=on
