apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: lakehouse
  labels:
    app: minio
spec:
  image: minio/minio:latest
  imagePullPolicy: IfNotPresent
  configuration:
    name: minio-configuration
  requestAutoCert: false
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
  buckets:
    - name: fluss
