apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: lakehouse
  labels:
    app: flink-jobmanager
spec:
  type: ClusterIP
  selector:
    app: flink-jobmanager
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
    - name: web
      port: 8081
      targetPort: 8081
    - name: blob
      port: 6124
      targetPort: 6124
