apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: lakehouse
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "mysql+mysqldb://airflow:airflow123@mysql:3306/airflow"
  AIRFLOW__CORE__FERNET_KEY: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
  AIRFLOW__WEBSERVER__SECRET_KEY: "lakehouse-airflow-webserver-secret"
