apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
  namespace: lakehouse
type: Opaque
stringData:
  SUPERSET_DATABASE_URI: "mysql+mysqldb://superset:superset123@mysql:3306/superset"
  SUPERSET_SECRET_KEY: "lakehouse-superset-secret-key-change-me"
  SUPERSET_ADMIN_USERNAME: "admin"
  SUPERSET_ADMIN_PASSWORD: "admin123"
  SUPERSET_ADMIN_FIRSTNAME: "Superset"
  SUPERSET_ADMIN_LASTNAME: "Admin"
  SUPERSET_ADMIN_EMAIL: "admin@lakehouse.local"
