apiVersion: v1
kind: Service
metadata:
  name: streampark-console
  namespace: lakehouse
  labels:
    app: streampark-console
spec:
  type: NodePort
  ports:
    - port: 10000
      targetPort: web
      name: web
      nodePort: 30100
  selector:
    app: streampark-console
