apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: lakehouse
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "lakehouse123"
  DS_DB_USER: "dolphinscheduler"
  DS_DB_PASSWORD: "ds123"
  STREAMPARK_DB_USER: "streampark"
  STREAMPARK_DB_PASSWORD: "streampark123"
