apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: lakehouse
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "lakehouse123"
  AIRFLOW_DB_USER: "airflow"
  AIRFLOW_DB_PASSWORD: "airflow123"
  STREAMPARK_DB_USER: "streampark"
  STREAMPARK_DB_PASSWORD: "streampark123"
  SUPERSET_DB_USER: "superset"
  SUPERSET_DB_PASSWORD: "superset123"
