apiVersion: v1
kind: Service
metadata:
  name: fluss-coordinator
  namespace: lakehouse
  labels:
    app: fluss-coordinator
spec:
  type: ClusterIP
  selector:
    app: fluss-coordinator
  ports:
    - name: rpc
      port: 9123
      targetPort: 9123
