apiVersion: v1
kind: ConfigMap
metadata:
  name: lakehouse-config
  namespace: lakehouse
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
        <property>
            <name>fs.s3a.access.key</name>
            <value>minioadmin</value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value>minioadmin</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>http://minio.lakehouse.svc.cluster.local</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
    </configuration>

  fluss-coordinator.properties: |
    zookeeper.address: zookeeper:2181
    remote.data.dir: s3://fluss/remote-data
    s3.endpoint: http://minio.lakehouse.svc.cluster.local
    s3.access-key: minioadmin
    s3.secret-key: minioadmin
    s3.path.style.access: true
    datalake.format: paimon
    datalake.paimon.metastore: filesystem
    datalake.paimon.warehouse: s3://fluss/paimon
    datalake.paimon.s3.endpoint: http://minio.lakehouse.svc.cluster.local
    datalake.paimon.s3.access-key: minioadmin
    datalake.paimon.s3.secret-key: minioadmin
    datalake.paimon.s3.path.style.access: true

  fluss-tablet.properties: |
    zookeeper.address: zookeeper:2181
    data.dir: /tmp/fluss/data
    remote.data.dir: s3://fluss/remote-data
    s3.endpoint: http://minio.lakehouse.svc.cluster.local
    s3.access-key: minioadmin
    s3.secret-key: minioadmin
    s3.path.style.access: true
    kv.snapshot.interval: 10s
    datalake.format: paimon
    datalake.paimon.metastore: filesystem
    datalake.paimon.warehouse: s3://fluss/paimon
    datalake.paimon.s3.endpoint: http://minio.lakehouse.svc.cluster.local
    datalake.paimon.s3.access-key: minioadmin
    datalake.paimon.s3.secret-key: minioadmin
    datalake.paimon.s3.path.style.access: true
