apiVersion: v1
kind: Secret
metadata:
  name: streampark-secret
  namespace: lakehouse
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "streampark"
  SPRING_DATASOURCE_PASSWORD: "streampark123"
