apiVersion: v1
kind: ConfigMap
metadata:
  name: doris-be-conf
  namespace: lakehouse
data:
  be.conf: |
    CUR_DATE=`date +%Y%m%d-%H%M%S`
    PPROF_TMPDIR="$DORIS_HOME/log/"
    JAVA_OPTS_FOR_JDK_17="-Xmx1024m -DlogPath=$DORIS_HOME/log/jni.log -Xlog:gc*:$DORIS_HOME/log/be.gc.log.$CUR_DATE:time,uptime:filecount=10,filesize=50M -Djavax.security.auth.useSubjectCredsOnly=false -Dsun.security.krb5.debug=true -Dsun.java.command=DorisBE -DJDBC_MIN_POOL=1 -DJDBC_MAX_POOL=100 -DJDBC_MAX_IDLE_TIME=300000 -DJDBC_MAX_WAIT_TIME=5000"
    be_port=9060
    webserver_port=8040
    heartbeat_service_port=9050
    brpc_port=8060
