apiVersion: v1
kind: ConfigMap
metadata:
  name: streampark-config
  namespace: lakehouse
data:
  application.yml: |
    server:
      port: 10000

    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/streampark?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}

    streampark:
      workspace:
        local: /opt/streampark/workspace
