apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: lakehouse
  labels:
    app: airflow-webserver
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: web
      name: web
      nodePort: 30080
  selector:
    app: airflow-webserver
